-- MySQL Script generated by MySQL Workbench
-- Qui 15 Jun 2017 10:56:13 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema zoologico
-- -----------------------------------------------------
-- Banco de dados fictício para armazenamento de informações de um zoológico para projeto AS Capacita

-- -----------------------------------------------------
-- Schema zoologico
--
-- Banco de dados fictício para armazenamento de informações de um zoológico para projeto AS Capacita
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zoologico` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `zoologico` ;

-- -----------------------------------------------------
-- Table `zoologico`.`Zoo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoologico`.`Zoo` (
  `idZoo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomeZoo` VARCHAR(250) NOT NULL,
  `enderecoZoo` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`idZoo`))
ENGINE = MyISAM
COMMENT = 'Armazena informações sobre o zoológico';


-- -----------------------------------------------------
-- Table `zoologico`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoologico`.`Funcionario` (
  `cdFuncionario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomeFuncionario` VARCHAR(200) NOT NULL,
  `cpfFuncionario` VARCHAR(20) NOT NULL,
  `dtNascFuncionario` DATE NOT NULL,
  `dtInicioFuncionario` DATE NOT NULL,
  PRIMARY KEY (`cdFuncionario`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `zoologico`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoologico`.`Usuario` (
  `idUsuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `loginUsuario` VARCHAR(45) NOT NULL,
  `senhaUsuario` VARCHAR(45) NOT NULL,
  `permissaoUsuario` VARCHAR(1) NOT NULL,
  `Funcionario_CdFuncionario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idUsuario`, `Funcionario_CdFuncionario`),
  INDEX `fk_Usuario_Funcionario1_idx` (`Funcionario_CdFuncionario` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `zoologico`.`Recinto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoologico`.`Recinto` (
  `idRecinto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descricaoRecinto` VARCHAR(250) NOT NULL,
  `nrRecinto` VARCHAR(45) NULL,
  PRIMARY KEY (`idRecinto`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `zoologico`.`Especie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoologico`.`Especie` (
  `idEspecie` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomeEspecie` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idEspecie`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `zoologico`.`Animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoologico`.`Animal` (
  `idAnimal` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomeAnimal` VARCHAR(100) NULL,
  `localNascAnimal` VARCHAR(100) NULL,
  `pesoAnimal` FLOAT NULL,
  `alturaAnimal` FLOAT NULL,
  `Recinto_idRecinto` INT UNSIGNED NOT NULL,
  `Especie_idEspecie` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idAnimal`),
  INDEX `fk_Animal_Recinto_idx` (`Recinto_idRecinto` ASC),
  INDEX `fk_Animal_Especie1_idx` (`Especie_idEspecie` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `zoologico`.`Visitante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoologico`.`Visitante` (
  `idVisitante` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomeVisitante` VARCHAR(200) NOT NULL,
  `dtNascVisitante` DATE NULL,
  PRIMARY KEY (`idVisitante`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `zoologico`.`Visita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoologico`.`Visita` (
  `idVisita` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dtVisita` VARCHAR(45) NOT NULL,
  `Visitante_idVisitante` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idVisita`),
  INDEX `fk_Visita_Visitante1_idx` (`Visitante_idVisitante` ASC))
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
